-- RAW + JPEG support migration example for ZenithPhoto.

ALTER TABLE photos ADD COLUMN raw_path TEXT NULL;
ALTER TABLE photos ADD COLUMN jpeg_path TEXT NULL;
ALTER TABLE photos ADD COLUMN has_raw INTEGER NOT NULL DEFAULT 0;

ALTER TABLE photos ADD COLUMN thumbnail BLOB NULL;
ALTER TABLE photos ADD COLUMN preview BLOB NULL;

ALTER TABLE photos ADD COLUMN capture_date TEXT NULL;
ALTER TABLE photos ADD COLUMN camera_make TEXT NULL;
ALTER TABLE photos ADD COLUMN camera_model TEXT NULL;
ALTER TABLE photos ADD COLUMN lens_model TEXT NULL;
ALTER TABLE photos ADD COLUMN focal_length REAL NULL;
ALTER TABLE photos ADD COLUMN shutter_speed REAL NULL;
ALTER TABLE photos ADD COLUMN aperture REAL NULL;
ALTER TABLE photos ADD COLUMN iso INTEGER NULL;
ALTER TABLE photos ADD COLUMN width INTEGER NULL;
ALTER TABLE photos ADD COLUMN height INTEGER NULL;
ALTER TABLE photos ADD COLUMN orientation INTEGER NULL;
